### ISSUE TITLE
Some services on the i2 Analyze server are unavailable.

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze#74]
Good morning,

We have a demo environment at Digital Ocean. After I did the upgrade to i2 Analyze 4.2.2 and analyze-containers v 2.7.0 I didn't get it working again.

1. After the upgrade I got the message 'Error: The leader Liberty was not elected in time.' when I deployed the config.
2. I did a clean deploy, but without success. After this I restarted the server.
3. After this I deployed the config again, and it seems to be successful.
4. But when I tried to use i2 Analyze via Chrome I received the error that some services are unavailable.

What can I do to fix this?

![image](https://github.com/i2group/analyze/assets/52672945/2a4e9e45-c990-46e5-9aef-5e56e410d2c9)
![image](https://github.com/i2group/analyze/assets/52672945/d0be4ade-4450-41cc-9720-8764810b73bb)
![image](https://github.com/i2group/analyze/assets/52672945/0dbb4151-7509-4b4e-a76f-1066e55bae99)
![image](https://github.com/i2group/analyze/assets/52672945/a129b214-396a-4bf6-895b-2cdc5b728eb2)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

Analyze containers related questions.issues might be best raised  against that repository: 

https://github.com/i2group/analyze-containers/issues

I will see if someone can look in to this for you.

Cheers

**Comment by sdorresteijn88** [comment]
Hi Anthony,

Thanks for your quick reply. Should I raise it also in the other repo, or should I do that next time?

**Comment by Anthony-Johnson-i2** [comment]
You are fine just leaving it here this time. :-)


Someone should be checking this for you shortly.

**Comment by sdorresteijn88** [comment]
A small update. In the liberty logs I found this error.

[ERROR   ] CWWKO0801E: The SSL connection cannot be initialized from the 172.18.0.8 host and 9,443 port on the remote client to the 152.32.200.117 host and 34,646 port on the local server. Exception: javax.net.ssl.SSLHandshakeException: No matching application layer protocol values
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:347)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:294)
        at java.base/sun.security.ssl.AlpnExtension$CHAlpnConsumer.consume(AlpnExtension.java:326)
        at java.base/sun.security.ssl.SSLExtension.consumeOnLoad(SSLExtension.java:592)
        at java.base/sun.security.ssl.SSLExtensions.consumeOnLoad(SSLExtensions.java:189)
        at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1051)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:843)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:802)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:782)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at com.ibm.ws.channel.ssl.internal.SSLUtils.handleHandshake(SSLUtils.java:756)
        at [internal classes]

**Comment by Matt-Hadfield-i2** [comment]
Hi [sdorresteijn88](https://github.com/sdorresteijn88), which set of steps did you follow to complete the upgrade?

https://i2group.github.io/analyze-containers/content/managing_upgrade_env.html

It looks like something might have gone wrong with the certificates.

**Comment by sdorresteijn88** [comment]
And I followed the pre reqs of course.

I removed the dev-environments-secrets, ran create-dev-environment, did a clean deploy and a normal deploy. But this didn't fix the issue.

**Comment by sdorresteijn88** [comment]
Weird, I changed the db from postgres to sql. Did all the steps again and now it works...

**Comment by Matt-Hadfield-i2** [comment]
> Weird, I changed the db from postgres to sql. Did all the steps again and now it works...

I must have been typing when you sent this.

If it is a certificate issue, this might make sense as it would be the first time using SQL Server it would use the new certificates. I would still try to run the renew-certificates command for Postgres and see if that fixes it.

**Comment by Anthony-Johnson-i2** [comment]
Thanks for engaging in this Matt.

I'm not surprised it didn't like TLS1.1  

 >>Client requested protocol TLSv1.1 is not enabled or supported in server context
 
 Odd that gets specified anywhere now as it was deprecated in 2021.

**Comment by sdorresteijn88** [comment]
The previous version ran on SQL as well. 

I changed it back to Postgres. Deployed it again and got the same error. 

I renew the certificates, as descripted in the link. The SSL errors are now gone, but it's still not working. 

[AUDIT   ] CWWKT0016I: Web application available (default_host): https://7b0c1caf1119:9443/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://7b0c1caf1119:9443/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://7b0c1caf1119:9443/IBMJMXConnectorREST/
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://7b0c1caf1119:9443/opal/
[WARNING ] CWNEN0070W: The javax.inject.Inject annotation class will not be recognized because it was loaded from the file:/opt/ol/wlp/usr/servers/defaultServer/apps/opal-services.war/WEB-INF/lib/javax.inject-1.jar location rather than from a product class loader.
[I2AVAILABILITY] 2023-09-04 13:32:40,162 INFO  ServerLeadershipMonitor        - I2ANALYZE_STATUS:0061 - Liberty leadership listener initializing...
[AUDIT   ] CWWKZ0001I: Application opal-services started in 19.575 seconds.
[AUDIT   ] CWWKF1037I: The server added the [javaMail-1.5, json-1.0, localConnector-1.0, monitor-1.0, mpConfig-1.2, mpMetrics-1.1, restConnector-2.0, websocket-1.0] features to the existing feature set.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, beanValidation-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, el-3.0, javaMail-1.5, jaxrs-2.1, jaxrsClient-2.1, jdbc-4.2, jndi-1.0, jpa-2.2, jpaContainer-2.2, json-1.0, jsonp-1.1, jsp-2.3, localConnector-1.0, monitor-1.0, mpConfig-1.2, mpMetrics-1.1, restConnector-2.0, servlet-4.0, ssl-1.0, websocket-1.0].
[AUDIT   ] CWWKF0013I: The server removed the following features: [appClientSupport-1.0, appSecurity-3.0, batch-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, j2eeManagement-1.1, jacc-1.5, jaspic-1.1, javaMail-1.6, javaee-8.0, jaxb-2.2, jaxws-2.2, jca-1.7, jcaInboundSecurity-1.0, jms-2.0, jsf-2.3, jsonb-1.0, managedBeans-1.0, mdb-3.2, wasJmsClient-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, webProfile-8.0, websocket-1.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 28.019 seconds.
[I2AVAILABILITY] 2023-09-04 13:32:41,266 WARN  ComponentAvailabilityCheck     - Information Store database appears to be offline, retrying...
[I2AVAILABILITY] 2023-09-04 13:32:41,270 WARN  ComponentAvailabilityCheck     - Information Store database appears to be offline, retrying...
[I2AVAILABILITY] 2023-09-04 13:32:41,273 WARN  ComponentAvailabilityCheck     - Unable to connect to the Information Store database.
javax.naming.NamingException: CWNEN1001E: The object referenced by the java:comp/env/ds/InfoStore JNDI name could not be instantiated. If the reference name maps to a JNDI name in the deployment descriptor bindings for the application performing the JNDI lookup, make sure that the JNDI name mapping in the deployment descriptor binding is correct. If the JNDI name mapping is correct, make sure the target resource can be resolved with the specified name relative to the default initial context. [Root exception is com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/ds/InfoStore reference.  The exception message was: CWNEN1006E: The server was unable to obtain an object for the ds/InfoStore-infostore binding with the javax.sql.DataSource type. The exception message was: java.sql.SQLNonTransientException: DSRA4000E: No implementations of javax.sql.ConnectionPoolDataSource are found for dataSource[ds/InfoStore-infostore-j2c-alias] with library jdbcDriver[postgres_postgresql_jdbc_jre11_jar]//com.ibm.ws.classloading.sharedlibrary(library)[default-0]. The name or location of JDBC driver JAR files might be incorrect or inaccessible. Searched in: []. Searched under packages: [].]
[I2AVAILABILITY] 2023-09-04 13:32:41,276 WARN  ComponentAvailabilityCheck     - The Information Store database is unavailable
[I2AVAILABILITY] 2023-09-04 13:32:41,280 INFO  ApplicationStateHandler        - I2ANALYZE_STATUS:0068 - The application is waiting for all components to be available before starting
[WARNING ] SRVE0190E: File not found: /js/service-worker/service-worker-immutable-ab8f145567e593b62dee.js
[WARNING ] SRVE0190E: File not found: /js/service-worker/service-worker-immutable-ab8f145567e593b62dee.js
[WARNING ] SRVE0190E: File not found: /js/service-worker/service-worker-immutable-ab8f145567e593b62dee.js
[WARNING ] SRVE0190E: File not found: /js/service-worker/service-worker-immutable-ab8f145567e593b62dee.js
[WARNING ] SRVE0190E: File not found: /js/service-worker/service-worker-immutable-ab8f145567e593b62dee.js

**Comment by Anthony-Johnson-i2** [comment]
I see that there has been no response to your last comment on this @sdorresteijn88.

Did  you manage to get this sorted yourself or are you waiting from a response from @Matt-Hadfield-i2 or one of the other developers  on the team?

**Comment by sdorresteijn88** [comment]
Hi Antony,

I didn't get an answer on this one. I have a work around by using SQL, so it's not urgent.

**Comment by Anthony-Johnson-i2** [comment]
Thank you for your reply Steven

Hi @Matt-Hadfield-i2 can you or one of your team look into this further for Steven as whilst it is not urgent, having to change the database flavour  to make things work should not be necessary.

Cheers

**Comment by Matt-Hadfield-i2** [comment]
Hi @sdorresteijn88 , have you tried deploying with Postgres again after we fixed the user permissions in your demo environment two weeks ago?

Thanks, Matt

**Comment by sdorresteijn88** [comment]
HI @Matt-Hadfield-i2 , I tried it this morning. But I still have the same issue.

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  I have been checking in with development on this since you last replied and will keep prodding them :-)
Have you resolved this yourself yet or have any of our folks been speaking with you directly?
Cheers

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  I am transferring this issue to the analyze-containers repository so that it has greater visibility for the correct team.

Cheers
